#ifndef LE_SOLVER_DEBUG_H
#define LE_SOLVER_DEBUG_H

#define ASSERT_MATRIX_RANGES
#define ASSERT_INCORRECT_ARGUMENTS

//#define PRINT_MATRIX_HUMAN_READABLE
#define PRINT_MATRIX_ELIMINATION_ITERATIONS

#endif //LE_SOLVER_DEBUG_H
